action/urls.py
#coding:utf-8
from django.conf.urls import url
from action.views import Update_host,task_test,Mytask,mytask_result,init2101,get_kuwoact,kuwo_act,del_kuwo_act,create_act,Cronttask,create_short_task,show_short_task,stop_short_task,upload_dianpian,show_shrot_task_log


urlpatterns = [
    url('^Update_host$', Update_host.as_view(), name="Update_host"),
    url('^task_test$', task_test.as_view(), name="task_test"),
    url('^$', Mytask.as_view(), name="mytask"),
    url('^result/(?P<active_code>.*)/$', mytask_result.as_view(), name="mytask_result"),
    url('^init/2101/$', init2101.as_view(), name="init2101"),
    url('^del_kuwo',del_kuwo_act.as_view(),name="del_kuwo_act"),
    url('^kuwo_act',kuwo_act.as_view(),name="kuwo_act"),
    url('^kuwo',get_kuwoact.as_view(),name="kuwo_act_fdl"),
    url('^create_act',create_act.as_view(),name="create_act"),
    url('^crontab',Cronttask.as_view(),name="cront_task"),
    url('^create_short_task',create_short_task.as_view(),name="short_task"),
    url('^short_task',show_short_task.as_view(),name="short_task_list"),
    url('^upload_dianpian',upload_dianpian.as_view(),name="upload_dianpian"),
    url('^task_log/(?P<active_code>.*)/$',show_shrot_task_log.as_view(),name="show_shrot_task_log"),
    url('^stop_short_task',stop_short_task.as_view(),name="stop_short_task"),
    url('^short_task',create_short_task.as_view(),name="short_task"),
    url('^kuwo',get_kuwoact.as_view(),name="kuwo_act_fdl")
]

dzbsm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from users.views import IndexView
from action.views import list_platform
import xadmin


urlpatterns = [
    url('^$', IndexView.as_view(), name="index"),
    url(r'^xadmin/', xadmin.site.urls),
    url('^index$', IndexView.as_view(), name="index"),
    url(r'^captcha/', include('captcha.urls')),
    url(r"^users/", include('users.urls', namespace="users")),
    url(r"^action/", include('action.urls', namespace="action")),
    url('^list_platform', list_platform.as_view(), name="list_platform"),
]

users/urls.py
#coding:utf-8
from django.conf.urls import url
from users.views import RegisterView,LoginView,ActiveUserView,LogoutView,ForgetPwdView,ResetView,UpdatePwdView,ModifyPwdView,SendEmailCodeView,UserInfoView


urlpatterns = [
    url('^info$', UserInfoView.as_view(), name="user_info"),
    url('^register', RegisterView.as_view(), name="register"),
    url('^login',LoginView.as_view(), name="login"),
    url('^logout$', LogoutView.as_view(), name="logout"),
    url('^forget_pwd$', ForgetPwdView.as_view(), name="forget_pwd"),
    url('^active/(?P<active_code>.*)/$',ActiveUserView.as_view(), name= "user_active"),
    url('^reset/(?P<active_code>.*)/$', ResetView.as_view(), name="reset_pwd"),
    url('^modify_pwd$', ModifyPwdView.as_view(), name="modify_pwd"),
    url('^update/pwd$', UpdatePwdView.as_view(), name="update_pwd"),
    url(r'^sendemail_code/$',SendEmailCodeView.as_view(),name="sendemail_code"),


]

users/forms.py
#coding:utf-8
from users.models import UserProfile
from  django import forms
from captcha.fields import CaptchaField


# 验证码form & 注册表单form
class RegisterForm(forms.Form):
    # 此处email与前端name需保持一致。
    email = forms.EmailField(required=True)
    # 密码不能小于5位
    password = forms.CharField(required=True, min_length=5)
    # 应用验证码 自定义错误输出key必须与异常一样
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})

# 激活时验证码实现
class ActiveForm(forms.Form):
    # 激活时不对邮箱密码做验证
    # 应用验证码 自定义错误输出key必须与异常一样
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})

# 登录表单验证
class LoginForm(forms.Form):
    # 用户名密码不能为空
    username = forms.CharField(required=True)
    # 密码不能小于5位
    password = forms.CharField(required=True, min_length=5)

# 忘记密码实现
class ForgetForm(forms.Form):
    # 此处email与前端name需保持一致。
    email = forms.EmailField(required=True)
    # 应用验证码 自定义错误输出key必须与异常一样
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})
# 重置密码form实现
class ModifyPwdForm(forms.Form):
    # 密码不能小于5位
    password1 = forms.CharField(required=True, min_length=5)
    # 密码不能小于5位
    password2 = forms.CharField(required=True, min_length=5)
# 用于个人中心修改个人信息
class UserInfoForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['nick_name','gender','birthday','address','mobile']

xadmin/views/base.py
import sys
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.utils.encoding import force_unicode
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import smart_unicode
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker


csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, basestring) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_unicode(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

    def init_request(self, *args, **kwargs):
        pass

    def init_plugin(self, *args, **kwargs):
        plugins = []
        for p in self.base_plugins:
            p.request = self.request
            p.user = self.user
            p.args = self.args
            p.kwargs = self.kwargs
            result = p.init_request(*args, **kwargs)
            if result is not False:
                plugins.append(p)
        self.plugins = plugins

    @filter_hook
    def get_context(self):
        return {'admin_view': self, 'media': self.media, 'base_template': self.base_template}

    @property
    def media(self):
        return self.get_media()

    @filter_hook
    def get_media(self):
        return forms.Media()


class CommAdminView(BaseAdminView):

    base_template = 'xadmin/base_site.html'
    menu_template = 'xadmin/includes/sitemenu_default.html'

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
        <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
<title> {% block titile %}首页 | DZBSM {% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %} {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
                <div  class=" header">
                        <div class="top">
        {% if request.user.is_authenticated %}
            <div class="wp">
             <div class="fl"><p><b></b></p></div>
                        <div class="personal">

                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="/static/{{ user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                        <dt><img width="80" height="80" src="/static/{{ user.image }}"/></dt>
                                        <dd>
                                            <h2>{{ user.nick_name }}</h2>
                                            <p>{{ user.username }}</p>
                                        </dd>
                                </dl>
                                <div class="btn">
                                        <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                        <a class="fr" href="{% url 'users:logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                        </a>
            </div>
    {% else %}
                                                <div class="wp">
                                        <div class="fl"><p><b></b></p></div>
                                        <!--登录后跳转-->


                      <a style="color:white" class="fr registerbtn" href="{% url "users:register" %}">注册</a>
                    <a style="color:white" class="fr loginbtn" href="{% url 'users:login'%}?next={{ request.path }}">登录</a>




                                </div>
{% endif %}
                        </div>

            <div class="middle">
                <div class="wp">
                </div>
            </div>


                        <nav>
                                <div class="nav">
                                        <div class="wp">
                                                <ul>
                                                    <li ><a href="/action/">任务</a></li>
                                                    <li ><a href="/action/init/2101/">2101初始化</a></li>
                                                    <li ><a href="/action/Update_host">更新主机列表</a></li>
                                                    <li ><a href="/action/kuwo_act">酷我活动管理(旧mesos)</a></li>
                                                    <li ><a href="/action/short_task">短任务管理(酷我活动本地版)</a></li>
                                                    <li ><a href="/action/crontab">定时任务结果</a></li>
                                                    <li ></li>
                                                </ul>
                                        </div>
                                </div>
                        </nav>

                        </div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
{% endblock %}

<footer>
                <div class="footer">
                        <div class="wp">
                        </div>
                        <p class="line"></p>
                        <div class="wp clear">
                        </div>
                </div>
        </footer>


<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static '' %}js/plugins/laydate/laydate.js"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
{% block custom_js %} {% endblock %}
</body>
</html>

templates/email_error.html
<h1>时间：{{time}}</h1>
<h1>主机组: {{group}}</h1>
<h2>playbook：{{playbook}} </h2>
<h3>任务状态：{{status}}</h3>

templates/email_forget.html
<h3 style="font-size: 22px;">快来找回您在dzbsm丢失的密码</h3>
                                                                                        <p style="font-size: 18px; ">点下面黄色框框重置密码！</p><div style="text-decoration: no
ne; outline: none; background-color: rgb(253, 216, 22); float: left; border-bottom: 2px solid rgb(246, 174, 18); color: rgb(51, 51, 51); margin-top: 8px; cursor: pointer; width
: 160px; height: 20px; line-height: 20px; text-align: center; padding: 5px 9px;"><a href="http://{{domain}}/users/reset/{{active_code}}" style="color: rgb(51, 51, 51);">点击进>
入重置密码页面</a></div>

templates/email_register.html
<p style="font-size: 18px; ">更感谢您注册了本站的账号</p><div style="text-decoration: no
ne; outline: none; background-color: rgb(253, 216, 22); float: left; border-bottom: 2px solid rgb(246, 174, 18); color: rgb(51, 51, 51); margin-top: 8px; cursor: pointer; width
: 160px; height: 20px; line-height: 20px; text-align: center; padding: 5px 9px;"><a href="http://{{domain}}/users/active/{{active_code}}" style="color: rgb(51, 51, 51);">点击以
激活您的账户</a></div>

templates/index.html
{% extends 'base.html' %}


{% load staticfiles %}
<!--crumbs start-->
{% block custom_bread %}
{% endblock %}


{% block content %}


{% endblock %}


{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

templates/init_2101.html
{% extends 'base.html' %}


{% load staticfiles %}
{% block custom_bread %}
{% endblock %}


{% block content %}

</br>
</br>

<div>
<h1 align="center"  style="color:red ; font-size:50px">空闲可用UID数量:{{ free_uid }}</h1></br>
<form class="clearfix" id="jsEditUserForm" autocomplete="off" method="post" action="{% url 'action:init2101'%}">
               
		初始化IP列表 (以,分隔)：<input type="text"  name="ip" id="ip" />
		<input class="button" type="submit" id="jsEditUserBtn" value="    保存    "/>
	{% csrf_token %}
</form>
</div>
<div>
						<h3>2101 机器列表</h3>
                                                  {% for group in groups  %}
                                                  {{ group }}</br>
                                                  {% endfor %}
<div>

{% endblock %}


{% block custom_js %}
{% endblock %}

templates/register.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>注册</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">

</head>
<body>
<div class="loginbox dialogbox">
    <h1>账号登录</h1>
    <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
    <div class="cont">
        <form id="jsLoginForm" autocomplete="off">
            <div class="box">
                <span class="word3">用户名</span>
                <input type="text" name="account_l" id="account_l" placeholder="手机号/邮箱" />
            </div>
            <div class="box">
                <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>
                <input type="password" name="password_l" id="password_l" placeholder="请输入您的密码"/>
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips"></div> <!--登录错误提示-->
            <div class="btns">
                <span><input type="checkbox" id="jsAutoLogin" />&nbsp;自动登录</span>
                <span class="forget btn fr">忘记密码</span>
            </div>
            <div class="button">
                <input type="button" value="登录" id="jsLoginBtn" />
            </div>
            <div class="btns">
                <span class="fr">没有账号？<span class="regist btn">立即注册</span></span>
            </div>
        </form>
    </div>
</div>
<div class="dialog" id="jsDialog">
    <!--提示弹出框-->
    <div class="successbox dialogbox" id="jsSuccessTips">
        <h1>成功提交</h1>
        <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
        <div class="cont">
            <h2>您的需求提交成功！</h2>
            <p></p>
        </div>
    </div>
    <div  class="noactivebox dialogbox" id="jsUnactiveForm" >
        <h1>邮件验证提示</h1>
        <div class="close jsCloseDialog"><img src="static/images/dig_close.png"/></div>
        <div class="center">
            <img src="/static/images/send.png"/>
            <p>我们已经向您的邮箱<span class="green" id="jsEmailToActive">12@13.com</span>发送了邮件，<br/>为保证您的账号安全，请及时验证邮箱</p>
            <p class="a"><a class="btn" id="jsGoToEmail" target="_blank" href="http://mail.qq.com">去邮箱验证</a></p>
            <p class="zy_success upmove"></p>
            <p style="display: none;" class="sendE2">没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件（<span class="c5c">60s</span>）</p>
            <p class="sendE">没收到，您可以查看您的垃圾邮件和被过滤邮件，<br/>也可以<span class="c5c green" id="jsSenEmailAgin" style="cursor: pointer;">再次发送验证邮件</span></p>
        </div>
    </div>
</div>

<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <ul class="fr hd-bar">
                <li><a href="/users/login">[登录]</a></li>
                <li class="active"><a href="/users/login">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="/"></a>
                <h1>用户注册</h1>
                <a class="index-font" href="/index">回到首页</a>
            </div>
            <div class="fl form-box">
                <div class="tab">
                    <!--<h2 class="active">手机注册</h2>-->
                    <h2>邮箱注册</h2>
                </div>
<!-- <div class="tab-form"> -->
                    <!--<form id="mobile_register_form" autocomplete="off">-->
                        <!--<div class="form-group marb20">-->
                            <!--<label>手&nbsp;机&nbsp;号</label>-->
                            <!--<input id="jsRegMobile" name="account" type="text" placeholder="请输入您的手机号码" />-->
                        <!--</div>-->
                    <!--<div class="form-group marb20" id="jsRefreshCode">
                            <label>验&nbsp;证&nbsp;码</label>
                           <input autocomplete="off" class="form-control-captcha mobile-register-captcha" id="mobile-register-captcha_1" name="captcha_m_1" placeholder="请输入验证码" type="text" /> <input class="form-control-captcha mobile-register-captcha" id="mobile-register-captcha_0" name="captcha_m_0" placeholder="请输入验证码" type="hidden" value="29953bacf7005e8469388b449d97d00d523c1706" /> &nbsp;<img src="/captcha/image/29953bacf7005e8469388b449d97d00d523c1706/" alt="captcha" class="captcha" />-->
                       <!--</div>-->
                        <!--<div class="clearfix">-->
                            <!--<div class="form-group marb8 verify-code">-->
                                <!--<label>短信验证码</label>-->
                                <!--<input id="jsPhoneRegCaptcha" name="mobile_code" type="text" placeholder="输入手机验证码" />-->
                            <!--</div>-->
                            <!--<input class="verify-code-btn sendcode" id="jsSendCode" value="发送验证码">-->
                        <!--</div>-->
                        <!--<div class="form-group marb8">-->
                            <!--<label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>-->
                            <!--<input id="jsPhoneRegPwd" name="password_m" type="password" placeholder="请输入6-20位非中文字符密码" />-->
                        <!--</div>-->
                        <!--<div class="error btns" id="jsMobileTips"></div>-->
                        <!--<div class="auto-box marb8">-->

                        <!--</div>-->
                        <!--<input class="btn btn-green" id="jsMobileRegBtn" type="button" value="注册并登录" />-->
                    <!--</form>-->
                <!--</div>-->
                <div class="tab-form">
                    <form id="email_register_form" method="post" action="/users/register" autocomplete="off">
                        <div class="form-group marb20 {% if register_form.email.errors %} errorput{% endif %}">
                            <label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</label>
                            <input  type="text" id="id_email" name="email" value="{% ifnotequal None register_form.email.value %}{{ register_form.email.value }}{% endifnotequal %}" placeholder="请输入您的邮箱地址" />
                        </div>
                        <div class="form-group marb8 {% if register_form.password.errors %} errorput{% endif %}">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"  value="{% ifnotequal None register_form.password.value %}{{ register_form.password.value }}{% endifnotequal %}" placeholder="请输入6-20位非中文字符密码" />
                        </div>
                        <div class="form-group marb8 captcha1 {% if register_form.captcha.errors %} errorput{% endif %}">
                            <label>验&nbsp;证&nbsp;码</label>
                           {{ register_form.captcha }}
                            {{ active_form.captcha }}
                        </div>
                        <div class="error btns" id="jsEmailTips">{% for key, error in register_form.errors.items %}{{ error }}{% endfor %}{{ msg }}</div>
                        <div class="auto-box marb8">
                        </div>
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录" />
                        {% csrf_token %}
                    </form>
                </div>
                <p class="form-p">已有账号？<a href="/users/login">[立即登录]</a></p>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/validateDialog.js"  type="text/javascript"></script>
<script src="/static/js/login.js"  type="text/javascript"></script>
</body>
</html>